name: "Tarball"

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

env:
  PROTON_GE_RELEASE: "5.22-GE-1"

jobs:
  build:
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Install required system packages using apt-fast"
        run: >-
          DEBIAN_FRONTEND=noninteractive apt-fast install --no-install-recommends -y 
          autoconf
          patch

      - name: "Checkout Proton GE Custom"
        uses: "actions/checkout@v2.3.4"
        with:
          repository: "GloriousEggroll/proton-ge-custom"
          ref: "${{ env.PROTON_GE_RELEASE }}"
          submodules: "recursive"
          fetch-depth: 0

      - name: "Apply patches"
        run: "./patches/protonprep-nofshack.sh"

      - name: "Cleanup"
        run: "find . -xtype f -iname *.orig -delete"

      - name: "Create .tar.xz"
        run: "tar --exclude='.git' --exclude='.' --exclude='..' -cJvf proton-ge-custom-src.tar.xz * .*"

      - name: "Create SHA256SUMS file"
        run: "sha256sum -b proton-ge-custom-src.tar.xz > SHA256SUMS"

      - name: "Delete existing release"
        uses: "dev-drprasad/delete-tag-and-release@v0.1.2"
        env:
          GITHUB_TOKEN: "${{ secrets.LCTRS_BOT_TOKEN }}"
        with:
          delete_release: true
          tag_name: "${{ env.PROTON_GE_RELEASE }}"

      - name: "Create release"
        uses: "softprops/action-gh-release@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.LCTRS_BOT_TOKEN }}"
        with:
          draft: false
          prerelease: false
          release_name: "${{ env.PROTON_GE_RELEASE }}"
          tag_name: "${{ env.PROTON_GE_RELEASE }}"
          files: |
             proton-ge-custom-src.tar.xz
             SHA256SUMS
